### PR TITLE
Possible Lithium 0.10.0 fix

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
Just removes the mixins entirely, untested yet.

### CODE REVIEW

**Comment by AurySystem** [comment]
yeh if it's working we'll merge this and push builds later

**Comment by sleepingdragoninn** [comment]
Confirmed working with latest qsl + lithium on the singularity pack - zombies will walk through vile stalks (not sure if they're supposed to try to avoid them)

**Comment by sleepingdragoninn** [comment]
Updated QFAPI and used the new FAPI entries for setting DAMAGE_OTHER

**Comment by sleepingdragoninn** [comment]
Tested and working, mobs avoid tubes and stalks and the blocks around them.

**Comment by AurySystem** [comment]
thanks y'all

**Pull request merged**
